import pytest


class TestExceptions:
    @pytest.mark.asyncio
    async def test_base(self):
        pass
